CREATE DATABASE IF NOT EXISTS CURSO_ANGULAR;
USE CURSO_ANGULAR;

CREATE TABLE PRODUCTS(
    id INT( 255 ) AUTO_INCREMENT NOT NULL,
    name VARCHAR( 255 ),
    description TEXT,
    price VARCHAR( 255 ),
    image VARCHAR( 255 ),
    CONSTRAINT PK_PRODUCTS PRIMARY KEY( id )
) ENGINE = InnoDb CHARSET = utf8 AUTO_INCREMENT = 1;