FROM php:5.6-apache
EXPOSE 80
COPY . /var/www/html
COPY ./php.ini /usr/local/etc/php/php.ini
RUN apt-get update
RUN apt-get install -y libzip-dev
RUN docker-php-ext-install zip
RUN apt-get install git -y
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer install
